Ton of fixes + changes
- Change to using wide strings (see: https://github.com/bl-sdk/PythonSDK/commit/2486ddd7c77be6fa762d078194ea825d49daaf96 )
- Fix compiler error C2102
- Generalize the StartupSDK hook to be in `Games.h`
- Do a ton of things with `FText`
  * An empty FText will return `""`
  * You can now do a set on an `UTextProperty` / `FText` that implements `FTextHistory_StringTableEntry`
- Fix an issue with logging when you do a `pyexec`
- Rename some functions a little bit, just case changes